/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stdint.h"
#include "Platform_Types.h"


//RCC
#define RCC_BASE		0x40021000
#define RCC_APB2ENR		*((vuint32_t*)(RCC_BASE   + 0x18))
//#define RCC_CFGR		*((vuint32_t*)(RCC_BASE   + 0x04))
//#define RCC_CR		*((vuint32_t*)(RCC_BASE   + 0x00))

//GPIOA
#define PortA_BASE 		0x40010800
#define GPIOA_CRH		*((vuint32_t*)(PortA_BASE + 0x04))
#define GPIOA_ODR		*((vuint32_t*)(PortA_BASE + 0x0C))
#define GPIOA_CRL		*((vuint32_t*)(PortA_BASE + 0x00))


//AFIO
#define AFIO_Base		0x40010000
#define AFIO_EXTICR1	*((vuint32_t*)(AFIO_Base + 0x08))

//EXTI
#define EXTI_Base		0x40010400
#define EXTI_IMR		*((vuint32_t*)(EXTI_Base + 0x00))
#define EXTI_RTSR		*((vuint32_t*)(EXTI_Base + 0x08))
#define EXTI_PR			*((vuint32_t*)(EXTI_Base + 0x14))

#define NVIC_ISER0		*((vuint32_t*)(0xE000E100))



void Clock_init()
{
	//	Bit 2 IOPAEN: IO port A clock enable
	//	 Set and cleared by software.
	//	 0: IO port A clock disabled
	//	 1: IO port A clock enabled

	RCC_APB2ENR |= 1 << 2;

	// 1: Alternate Function IO clock enabled
	RCC_APB2ENR |= (1 << 0);
}

void GPIOA_init()
{
	//Pin 13 port A output
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	//Pin 0 Port A input Floating Point
	GPIOA_CRL |= (0b01 << 2);
}


int main(void)
{
	Clock_init();
	GPIOA_init();

	//Map GPIOA Pin0 to EXTI0
	AFIO_EXTICR1 |= (0b0000 << 0);

	//Enable Rising Edge of EXTI0
	EXTI_RTSR |= 1 << 0;

	//Enable EXTI0 (Mask 1)
	EXTI_IMR |= 1<< 0;

	//Enable NVIC Irq6 <<>> EXTI0
	NVIC_ISER0 |= (1 << 6);

	while(1);
	return 0;
}

void EXTI0_IRQHandler()
{
	//EXTI0 on PortA >> Pin0 _|- rising edge
	//Toggle bit 13
	GPIOA_ODR ^= 1 << 13;

	//Reset Pending Value
	EXTI_PR |= 1 << 0;
}
