/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32_F103C6_GPIO_drivers.h"
#include "STM32F103x6.h"
#include "STM32_F103C6_EXTI_drivers.h"
#include "LCD.h"
#include "keypad.h"
#include "Seven_Segmant.h"

extern char Seven_Seg_DISPLAY[10];
uint8 IRQ_Flag;


void wait(int x)
{
	uint32_t i, j;
	for (i = 0; i < x; i++)
		for (j = 0; j < 255; j++)
			;
}

void EXTI9_CallBack(void)
{
	IRQ_Flag = 1;
	LCD_WRITE_STRING("IRQ EXTI9 has Happped");
	wait(500);
}

int main(void)
{
	//Enable CLokc
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	LCD_INIT();
	LCD_clear_screen();

	//Initialize Interrupt
	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_RISING;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_CallBack;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enable;

	MCAL_EXTI_GPIO_Init(&EXTI_CFG);

	IRQ_Flag = 1;

	while(1)
	{
		if(IRQ_Flag)
		{
			LCD_clear_screen();
			IRQ_Flag = 0;
		}

	}
	return 0;
}
