/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32_F103C6_GPIO_drivers.h"
#include "STM32F103x6.h"
#include "STM32_F103C6_EXTI_drivers.h"
#include "LCD.h"
#include "STM32_F103C6_USART_drivers.h"

unsigned char ch;


void Mina_UART_IRQ_CallBack(void)
{
	MCAL_UART_RecieveData(USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);
}


int main(void)
{
	//Enable CLokc
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

	LCD_INIT();

	//Uart Enable
	UART_PinConfig_t uartCFG;
	uartCFG.BaudRate = USART_BaudRate_115200;
	uartCFG.Hw_FlowCtl = USART_Hw_FlowCtl_NONE;

	uartCFG.IRQ_Enable = USART_IRQ_Enable_RXNEIE;
	uartCFG.P_IRQ_CallBack = Mina_UART_IRQ_CallBack;

	uartCFG.Mode = USART_MODE_TX_RX;
	uartCFG.Parity = USART_Parity_NONE;
	uartCFG.Payload_Length = USART_Payload_Length_8B;
	uartCFG.StopBit = USART_StopBit_1;

	MCAL_UART_Init(USART1, &uartCFG);
	MCAL_UART_GPIO_Set_Pins(USART1);



	while(1)
	{


	}
	return 0;
}
