/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32_F103C6_GPIO_drivers.h"
#include "STM32F103x6.h"



void Clock_init()
{
	//Enable Clock GPIOA
	RCC_GPIOA_CLK_EN();

	//Enable IOPBEN : IO port B clock enable
	RCC_GPIOB_CLK_EN();
}

void GPIO_init()
{
	GPIO_PinConfig_t PinConfig;

	//A1 Set as Input Floating
	PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	PinConfig.GPIO_Mode = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinConfig);

	//B1 Set as output Pull & Push
	PinConfig.GPIO_PinNumber = GPIO_PIN_1;
	PinConfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	PinConfig.GPIO_Output_Speed = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, &PinConfig);


	//A13 Set as Input Floating
	PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	PinConfig.GPIO_Mode = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinConfig);

	//B13 Set as output Pull & Push
	PinConfig.GPIO_PinNumber = GPIO_PIN_13;
	PinConfig.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	PinConfig.GPIO_Output_Speed = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, &PinConfig);
}

void wait(int x)
{
	vuint32_t i, j;
	for(i = 0; i < x; i++)
		for(j = 0;j < 255; j++);
}

int main(void)
{
	Clock_init();
	GPIO_init();
	GPIOB->ODR &= ~(1 << 1);

	while(1)
	{

		//PA1
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) //External Pull Up resistance
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) //Single Pressed
			{
				//do nothing while pressed
			}
		}

		//PA13
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 0) //Pull down resistor & Multi press
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}

		wait(1);
	}
	return 0;
}
