/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stdint.h"
#include "Platform_Types.h"


//RCC
#define RCC_BASE		0x40021000
#define RCC_APB2ENR		*((vuint32_t*)(RCC_BASE   + 0x18))
//#define RCC_CFGR		*((vuint32_t*)(RCC_BASE   + 0x04))
//#define RCC_CR		*((vuint32_t*)(RCC_BASE   + 0x00))

//GPIOA
#define PortA_BASE 		0x40010800
#define GPIOA_CRL		*((vuint32_t*)(PortA_BASE + 0x00))
#define GPIOA_CRH		*((vuint32_t*)(PortA_BASE + 0x04))
#define GPIOA_ODR		*((vuint32_t*)(PortA_BASE + 0x0C))
#define GPIOA_IDR		*((vuint32_t*)(PortA_BASE + 0x08))

#define PortB_BASE 		0x40010C00
#define GPIOB_CRL		*((vuint32_t*)(PortB_BASE + 0x00))
#define GPIOB_CRH		*((vuint32_t*)(PortB_BASE + 0x04))
#define GPIOB_ODR		*((vuint32_t*)(PortB_BASE + 0x0C))
#define GPIOB_IDR		*((vuint32_t*)(PortB_BASE + 0x08))


void Clock_init()
{
	//	Bit 2 IOPAEN: IO port A clock enable
	//	 Set and cleared by software.
	//	 0: IO port A clock disabled
	//	 1: IO port A clock enabled

	RCC_APB2ENR |= 1 << 2;

	//Enable IOPBEN : IO port B clock enable
	RCC_APB2ENR |= 1 << 3;
}

void GPIO_init()
{
	GPIOA_CRL = 0x0;
	GPIOB_CRL = 0x0;
	GPIOA_CRH = 0x0;
	GPIOB_CRH = 0x0;

	//A1 Set as Input Floating
	GPIOA_CRL |=  (0b01 << 6);

	//B1 Set as output Pull & Push
	GPIOB_CRL |=  (0b01 << 4);
	GPIOB_CRL &= ~(0b11 << 6);


	//A13 Set as Input Floating
	GPIOA_CRH |=  (0b01 << 22);

	//B13 Set as output Pull & Push
	GPIOB_CRH |=  (0b01 << 20);
	GPIOB_CRH &= ~(0b11 << 22);
}

void wait(int x)
{
	vuint32_t i, j;
	for(i = 0; i < x; i++)
		for(j = 0;j < 255; j++);
}

int main(void)
{
	Clock_init();
	GPIO_init();

	while(1)
	{

		//PA1
		if(((GPIOA_IDR & (1 << 1)) >> 1) == 0) //External Pull Up resistance
		{
			GPIOB_ODR ^= (1 << 1);
			while(((GPIOA_IDR & (1 << 1)) >> 1) == 0) //Single Pressed
			{
				//do nothing while pressed
			}
		}

		//PA13
		if(((GPIOA_IDR & (1 << 13)) >> 13) == 1) //Pull down resistor & Multi press
		{
			GPIOB_ODR ^= (1 << 13);
		}

		wait(1);
	}
	return 0;
}

